# Generated by Django 4.1.4 on 2023-12-19 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_alter_answer_downvotes_alter_answer_upvotes_reportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='user_report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
